### ISSUE TITLE
npm install spectral-workbench failed

### ISSUE THREAD

**Issue by shenzj1994** [publiclab/spectral-workbench.js#51]
Please describe your problem in detail, including:

### What happened before you saw the error
Run 'npm install spectral-workbench'

### What you expected to happen
It should install, I guess.

### Browser, version, and operating system
Node container in Docker.
Node v9.5.0
(to help reproduce the issue)

### Output
root@6198d100cf95:/data/test# npm install spectral-workbench
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130

> contextify@0.1.15 install /data/test/node_modules/contextify
> node-gyp rebuild

make: Entering directory '/data/test/node_modules/contextify/build'
  CXX(target) Release/obj.target/contextify/src/contextify.o
../src/contextify.cc: In static member function 'static v8::Local<v8::Context> ContextWrap::createV8Context(v8::Local<v8::Object>)':
../src/contextify.cc:131:68: warning: 'v8::Local<v8::Object> v8::Function::NewInstance() const' is deprecated (declared at /root/.node-gyp/9.5.0/include/node/v8.h:3848): Use maybe version [-Wdeprecated-declarations]
         Local<Object> wrapper = Nan::New(constructor)->NewInstance();
                                                                    ^
../src/contextify.cc:150:16: error: 'class v8::ObjectTemplate' has no member named 'SetAccessCheckCallbacks'
         otmpl->SetAccessCheckCallbacks(GlobalPropertyNamedAccessCheck,
                ^
../src/contextify.cc: In static member function 'static void ContextWrap::GlobalPropertyGetter(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Value>&)':
../src/contextify.cc:182:80: warning: 'v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)' is deprecated (declared at /root/.node-gyp/9.5.0/include/node/v8.h:3400): Use maybe version [-Wdeprecated-declarations]
         Local<Value> rv = Nan::New(ctx->sandbox)->GetRealNamedProperty(property);
                                                                                ^
../src/contextify.cc: In static member function 'static void ContextWrap::GlobalPropertyQuery(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Integer>&)':
../src/contextify.cc:209:67: warning: 'v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)' is deprecated (declared at /root/.node-gyp/9.5.0/include/node/v8.h:3400): Use maybe version [-Wdeprecated-declarations]
         if (!Nan::New(ctx->sandbox)->GetRealNamedProperty(property).IsEmpty() ||
                                                                   ^
../src/contextify.cc:210:71: warning: 'v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)' is deprecated (declared at /root/.node-gyp/9.5.0/include/node/v8.h:3400): Use maybe version [-Wdeprecated-declarations]
             !Nan::New(ctx->proxyGlobal)->GetRealNamedProperty(property).IsEmpty()) {
                                                                       ^
contextify.target.mk:95: recipe for target 'Release/obj.target/contextify/src/contextify.o' failed
make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
make: Leaving directory '/data/test/node_modules/contextify/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:160:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.9.60-linuxkit-aufs
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /data/test/node_modules/contextify
gyp ERR! node -v v9.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/data/test/package.json'
npm WARN test No description
npm WARN test No repository field.
npm WARN test No README data
npm WARN test No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contextify@0.1.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-06T08_44_21_917Z-debug.log

**Comment by jywarren** [comment]
Oh, this is no good! Have you figured out a way around it? It's during compiling the `contextify` module: https://www.npmjs.com/package/contextify maybe a more recent version is needed in our package.json or something that depends on `contexify`? Could be worth checking their repository to see if others have seen a similar issue?

**Comment by shenzj1994** [comment]
Haven't check these yet but I will take a look later...

**Comment by jtunis-pg** [comment]
Is there a known package configuration that works around this issue?

**Comment by jywarren** [comment]
I'm not sure - have you checked on `contextify`'s issue tracker, or potentially a more recent version of contextify? Contextify says it's not longer needed:

> https://www.npmjs.com/package/contextify

Do you know where it's being included? 

https://github.com/publiclab/spectral-workbench.js/blob/master/package.json#L26-L29

**Comment by jtunis-pg** [comment]
Unsure where it's being included. I believe it's a UI-related package. Luckily I only needed the spectral-workbench backend and managed to get a function spectral-workbench.js with only having installed Cairo, and the Canvas and Request npm packages.

**Comment by jywarren** [comment]
https://github.com/publiclab/spectral-workbench.js/issues/77 may include some helpful hints...!

> Issue resolved by updating all the packages.
